### ISSUE TITLE
AcquireWithin should take a context.Context

### ISSUE THREAD

**Issue by kevinburke** [abiosoft/semaphore#4]
It would be easy enough to wait for either ctx.Done() or for a resource to become available.

**Comment by abiosoft** [comment]
This was written long before the context package. I plan to refactor it to take a context.

**Comment by abiosoft** [comment]
I'm thinking of adding an `AcquireContext`.

**Comment by abiosoft** [comment]
Now there is `AcquireContext` and you can use a `context.WithCancel` if required. https://godoc.org/github.com/abiosoft/semaphore#Semaphore.AcquireContext.

`AcquireWithin` has also been modified to simply use a `context.WithTimeout`.
